export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT"
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS"
export const GET_LIST_PRODUCT_FAIL = "GET_LIST_PRODUCT_FAIL"

export const GET_FILTER_LIST_PRODUCT = "GET_FILTER_LIST_PRODUCT"
export const GET_FILTER_LIST_PRODUCT_SUCCESS = "GET_FILTER_LIST_PRODUCT_SUCCESS"
export const GET_FILTER_LIST_PRODUCT_FAIL = "GET_FILTER_LIST_PRODUCT_FAIL"

export const WP_GET_LIST_PRODUCT = "WP_GET_LIST_PRODUCT"
export const WP_GET_LIST_PRODUCT_SUCCESS = "WP_GET_LIST_PRODUCT_SUCCESS"
export const WP_GET_LIST_PRODUCT_FAIL = "WP_GET_LIST_PRODUCT_FAIL"
