export const GET_BANNER = "GET_BANNER"
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS"
export const GET_BANNER_FAIL = "GET_BANNER_FAIL"

export const POST_BANNER = "POST_BANNER"
export const POST_BANNER_SUCCESS = "POST_BANNER_SUCCESS"
export const POST_BANNER_FAIL = "POST_BANNER_FAIL"

export const DELETE_BANNER = "DELETE_BANNER"
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS"
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL"